// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://ksrcwjszmoywsofhlgmz.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzcmN3anN6bW95d3NvZmhsZ216Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI3MDg4OTYsImV4cCI6MjA0ODI4NDg5Nn0.1P1ttGsdBKFdFMcuBYL9GbUkBY6K4-JRZqwHag2DAA0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);